version: 5.5.0.4
type: common
authorName: "Ilya I"
moduleName: "MergeProfiles"
description: "The MergeProfiles module combines customer orders into a single profile."
minorRequiredCoreVersion: 0
dependsOn: {}
incompatibleWith: {}
showSettingsForm: false
canDisable: true